### ISSUE TITLE
Please provide binaries for Windows

### ISSUE THREAD

**Issue by g-berthiaume** [orhun/binsider#15]
My use case:
I'm a Windows user developing embedded systems using cross-compilers to produce elf files.
This tool would be great for analyzing the produced binary.

Thanks for your work!

**Comment by orhun** [comment]
Windows binaries will be available with the next release with the following exceptions:

- Dynamic analysis feature is not supported, since [`lurk`](https://github.com/JakWai01/lurk) is not designed to run on Windows and I need to come up with something else for that.
- See #35 (good first issue if you want to contribute!!)

**Comment by g-berthiaume** [comment]
That's great ! looking forward to it!

**Comment by orhun** [comment]
Windows binaries are now available in https://github.com/orhun/binsider/releases/tag/v0.2.0
